export const bloodType = [
  {
    id: 1,
    name: "All",
    value: "",
  },
  {
    id: 2,
    name: "A+",
    value: "A_POSITIVE",
  },
  {
    id: 3,
    name: "A-",
    value: "A_NEGATIVE",
  },
  {
    id: 4,
    name: "B+",
    value: "B_POSITIVE",
  },
  {
    id: 5,
    name: "B-",
    value: "B_NEGATIVE",
  },
  {
    id: 6,
    name: "AB+",
    value: "AB_POSITIVE",
  },
  {
    id: 7,
    name: "AB-",
    value: "AB_NEGATIVE",
  },
  {
    id: 8,
    name: "O+",
    value: "O_POSITIVE",
  },
  {
    id: 9,
    name: "O-",
    value: "O_NEGATIVE",
  },
];
export const bloodTypeSelect = [
  {
    id: 2,
    name: "A+",
    value: "A_POSITIVE",
  },
  {
    id: 3,
    name: "A-",
    value: "A_NEGATIVE",
  },
  {
    id: 4,
    name: "B+",
    value: "B_POSITIVE",
  },
  {
    id: 5,
    name: "B-",
    value: "B_NEGATIVE",
  },
  {
    id: 6,
    name: "AB+",
    value: "AB_POSITIVE",
  },
  {
    id: 7,
    name: "AB-",
    value: "AB_NEGATIVE",
  },
  {
    id: 8,
    name: "O+",
    value: "O_POSITIVE",
  },
  {
    id: 9,
    name: "O-",
    value: "O_NEGATIVE",
  },
];

export const availabilityType = [
  {
    id: 1,
    name: "All",
    value: "",
  },
  {
    id: 2,
    name: "Available",
    value: "true",
  },
  {
    id: 3,
    name: "Unavailable",
    value: "false",
  },
];

export const districtsOfBangladesh = [
  { id: 1, name: "All", value: "" },
  { id: 2, name: "Barguna", value: "Barguna" },
  { id: 3, name: "Barishal", value: "Barishal" },
  { id: 4, name: "Bhola", value: "Bhola" },
  { id: 5, name: "Jhalokathi", value: "Jhalokathi" },
  { id: 6, name: "Patuakhali", value: "Patuakhali" },
  { id: 7, name: "Pirojpur", value: "Pirojpur" },
  { id: 8, name: "Bandarban", value: "Bandarban" },
  { id: 9, name: "Brahmanbaria", value: "Brahmanbaria" },
  { id: 10, name: "Chandpur", value: "Chandpur" },
  { id: 11, name: "Chattogram", value: "Chattogram" },
  { id: 12, name: "Cumilla", value: "Cumilla" },
  { id: 13, name: "Cox's Bazar", value: "Cox's Bazar" },
  { id: 14, name: "Feni", value: "Feni" },
  { id: 15, name: "Khagrachari", value: "Khagrachari" },
  { id: 16, name: "Lakshmipur", value: "Lakshmipur" },
  { id: 17, name: "Noakhali", value: "Noakhali" },
  { id: 18, name: "Rangamati", value: "Rangamati" },
  { id: 19, name: "Dhaka", value: "Dhaka" },
  { id: 20, name: "Faridpur", value: "Faridpur" },
  { id: 21, name: "Gazipur", value: "Gazipur" },
  { id: 22, name: "Gopalganj", value: "Gopalganj" },
  { id: 23, name: "Kishoreganj", value: "Kishoreganj" },
  { id: 24, name: "Madaripur", value: "Madaripur" },
  { id: 25, name: "Manikganj", value: "Manikganj" },
  { id: 26, name: "Munshiganj", value: "Munshiganj" },
  { id: 27, name: "Narayanganj", value: "Narayanganj" },
  { id: 28, name: "Narsingdi", value: "Narsingdi" },
  { id: 29, name: "Rajbari", value: "Rajbari" },
  { id: 30, name: "Shariatpur", value: "Shariatpur" },
  { id: 31, name: "Tangail", value: "Tangail" },
  { id: 32, name: "Bagerhat", value: "Bagerhat" },
  { id: 33, name: "Chuadanga", value: "Chuadanga" },
  { id: 34, name: "Jashore", value: "Jashore" },
  { id: 35, name: "Jhenaidah", value: "Jhenaidah" },
  { id: 36, name: "Khulna", value: "Khulna" },
  { id: 37, name: "Kushtia", value: "Kushtia" },
  { id: 38, name: "Magura", value: "Magura" },
  { id: 39, name: "Meherpur", value: "Meherpur" },
  { id: 40, name: "Narail", value: "Narail" },
  { id: 41, name: "Satkhira", value: "Satkhira" },
  { id: 42, name: "Jamalpur", value: "Jamalpur" },
  { id: 43, name: "Mymensingh", value: "Mymensingh" },
  { id: 44, name: "Netrokona", value: "Netrokona" },
  { id: 45, name: "Sherpur", value: "Sherpur" },
  { id: 46, name: "Bogura", value: "Bogura" },
  { id: 47, name: "Joypurhat", value: "Joypurhat" },
  { id: 48, name: "Naogaon", value: "Naogaon" },
  { id: 49, name: "Natore", value: "Natore" },
  { id: 50, name: "Pabna", value: "Pabna" },
  { id: 51, name: "Rajshahi", value: "Rajshahi" },
  { id: 52, name: "Sirajganj", value: "Sirajganj" },
  { id: 53, name: "Dinajpur", value: "Dinajpur" },
  { id: 54, name: "Gaibandha", value: "Gaibandha" },
  { id: 55, name: "Kurigram", value: "Kurigram" },
  { id: 56, name: "Lalmonirhat", value: "Lalmonirhat" },
  { id: 57, name: "Nilphamari", value: "Nilphamari" },
  { id: 58, name: "Panchagarh", value: "Panchagarh" },
  { id: 59, name: "Rangpur", value: "Rangpur" },
  { id: 60, name: "Thakurgaon", value: "Thakurgaon" },
  { id: 61, name: "Habiganj", value: "Habiganj" },
  { id: 62, name: "Maulvibazar", value: "Maulvibazar" },
  { id: 63, name: "Sunamganj", value: "Sunamganj" },
  { id: 64, name: "Sylhet", value: "Sylhet" },
];
